# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           ":title/"
relative_permalinks: false

# Setup
title:               'Amit Patel'
tagline:             ''
description:         'Ramblings and notes collected from lessons learned building real life webapps.'
url:                 'https://amitpatel.xyz'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              'Amit Patel'
  email:             'amit.savani@gmail.com'

social:
  github: https://github.com/amitsavani
  stack_overflow: https://stackoverflow.com/users/398863/amit-patel
  twitter: https://twitter.com/amit_savani


# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]